### ISSUE TITLE
socialize `docker`

### ISSUE THREAD

**Issue by msuchard** [OHDSI/SemaglutideNaionCharApp#3]
to better socialize `docker` across the community, please provide (in README.md?) instructions on how to build / deploy.

**Comment by anthonysena** [comment]
I've updated the `README` in https://github.com/OHDSI/SemaglutideNaionCharApp/commit/2f8dacdf2ea75d512082a5acc638ce40fe7a702e. If you have any suggestions on how to improve clarity to better socialize Docker for the community please re-open and add your comments to this issue and I'll make the revisions. Thanks!
